PROPERTIES_LIST = [
    "Last_form",
    "Rarity",
    "Name (E)",
    "Name (J)",
    "Level",
    "PV",
    "KB",
    "Movement Speed",
    "AP",
    "DPS",
    "Target",
    "Attack Frequency",
    "Range",
    "Cost",
    "Respawn",
    "Ability",
    "Strength_White",
    "Strength_Red",
    "Strength_Floating",
    "Strength_Black",
    "Strength_Metal",
    "Strength_Angel",
    "Strength_Alien",
    "Strength_Zombies",
    "Strength_Relic",
    "Resist_White",
    "Resist_Red",
    "Resist_Floating",
    "Resist_Black",
    "Resist_Metal",
    "Resist_Angel",
    "Resist_Alien",
    "Resist_Zombies",
    "Resist_Relic",
    "Shockwave",
    "Critic",
    "owned",
]
